
- hosts: all
  remote_user: admin
  become_user: root
  gather_facts: false
  tasks:
   - name: waiting for server to be stopped
     local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped timeout=300
     become: false
